/**
 * Firebase Data Connect Connector (Stub for Development)
 * 
 * This is a minimal stub connector to allow Data Connect initialization.
 * In production, this should be auto-generated by running:
 *   firebase dataconnect:build
 * 
 * TODO: Generate proper connector when Data Connect is fully configured in Firebase Console
 */

export const connector = {
  // Stub connector object - will be replaced with auto-generated one
  _connector: true,
  projectId: process.env.NEXT_PUBLIC_DATA_CONNECT_PROJECT_ID,
  serviceId: process.env.NEXT_PUBLIC_DATA_CONNECT_SERVICE_ID,
  location: process.env.NEXT_PUBLIC_DATA_CONNECT_LOCATION,
};
