/**
 * Firebase Data Connect Setup
 * Initializes connection to Firebase SQL (PostgreSQL)
 * 
 * Environment variables required:
 * - NEXT_PUBLIC_DATA_CONNECT_PROJECT_ID
 * - NEXT_PUBLIC_DATA_CONNECT_SERVICE_ID
 * - NEXT_PUBLIC_DATA_CONNECT_LOCATION
 * 
 * NOTE: Data Connect is OPTIONAL. The app falls back to localStorage for all data operations.
 * To enable Data Connect:
 * 1. Set up Data Connect in Firebase Console
 * 2. Run: firebase dataconnect:build
 * 3. This generates the required connector file
 */

// Data Connect is optional - if initialization fails, we use localStorage
let dataConnectInitialized = false;
let dataConnectAvailable = false;

/**
 * Initialize Data Connect (called once on app startup)
 * Safe to fail - the app will work with localStorage
 */
export function initializeDataConnect() {
  if (dataConnectInitialized) return;
  dataConnectInitialized = true;

  try {
    const projectId = process.env.NEXT_PUBLIC_DATA_CONNECT_PROJECT_ID;
    const serviceId = process.env.NEXT_PUBLIC_DATA_CONNECT_SERVICE_ID;
    const location = process.env.NEXT_PUBLIC_DATA_CONNECT_LOCATION;
    
    if (!projectId || !serviceId || !location) {
      console.log('Data Connect not configured. Using localStorage for data storage.');
      return;
    }

    // Try to use Data Connect if available
    try {
      require('@firebase/data-connect');
      dataConnectAvailable = true;
      console.log('Data Connect available - will use SQL when configured in Firebase Console');
    } catch {
      console.log('Data Connect SDK not ready - using localStorage for data storage');
    }
  } catch (error) {
    // Silently fail - localStorage will be used as fallback
  }
}

/**
 * Check if Data Connect is available
 */
export function isDataConnectAvailable(): boolean {
  return dataConnectAvailable;
}

/**
 * Get or initialize Data Connect instance
 * Returns null if not available - this is OK, we fall back to localStorage
 */
export function getDataConnectInstance() {
  if (!dataConnectAvailable) {
    return null;
  }
  
  try {
    // This would be called after connector is properly generated by Firebase CLI
    return null; // Placeholder for future implementation
  } catch (error) {
    return null;
  }
}

/**
 * Execute Data Connect query
 * Returns null if Data Connect not available - caller will use localStorage
 */
export async function executeQuery<T>(
  query: any,
  variables?: Record<string, any>
): Promise<T | null> {
  if (!isDataConnectAvailable()) {
    return null;
  }
  
  try {
    const { execute } = require('@firebase/data-connect');
    const dataConnect = getDataConnectInstance();
    
    if (!dataConnect) {
      return null;
    }
    
    console.log('Executing Data Connect query:', { variables });
    const result = await execute(dataConnect, query, variables);
    console.log('Query result:', result.data);
    
    return result.data as T;
  } catch (error) {
    console.warn('Data Connect query error (using localStorage):', error);
    return null;
  }
}

/**
 * Execute Data Connect mutation
 * Returns null if Data Connect not available - caller will use localStorage
 */
export async function executeMutation<T>(
  mutation: any,
  variables?: Record<string, any>
): Promise<T | null> {
  if (!isDataConnectAvailable()) {
    return null;
  }
  
  try {
    const { execute } = require('@firebase/data-connect');
    const dataConnect = getDataConnectInstance();
    
    if (!dataConnect) {
      return null;
    }
    
    console.log('Executing Data Connect mutation:', { variables });
    const result = await execute(dataConnect, mutation, variables);
    console.log('Mutation result:', result.data);
    
    return result.data as T;
  } catch (error) {
    console.warn('Data Connect mutation error (using localStorage):', error);
    return null;
  }
}

/**
 * Utility to handle Data Connect errors
 * Maps Data Connect errors to user-friendly Azerbaijani messages
 */
export function handleDataConnectError(error: any): string {
  const message = error?.message || 'Verilənlər bazasına bağlantı xətası';
  
  // Map specific errors to user-friendly messages in Azerbaijani
  if (message.includes('ALREADY_EXISTS')) {
    return 'Bu element artıq mövcuddur';
  }
  if (message.includes('NOT_FOUND')) {
    return 'Element tapılmadı';
  }
  if (message.includes('PERMISSION_DENIED')) {
    return 'Bu əməliyyatı yerinə yetirmək üçün icazəniz yoxdur';
  }
  if (message.includes('INVALID_ARGUMENT')) {
    return 'Düzgün olmayan arqument göndərildi';
  }
  if (message.includes('UNAVAILABLE')) {
    return 'Verilənlər bazası hazırda əlçatışmaz';
  }
  
  return message;
}
